from __future__ import annotations

import json
import re

import pytest

from xai_physics.eval.replay_llm_dataset import compare_answer
from xai_physics.hybrid.equations_candidates import generate_equations_candidate_schemas
from xai_physics.llm.schema_pipeline import solve_problem_with_llm
from xai_physics.schema_solver import solve_schema


class FakeSchemaLLM:
    def __init__(self, output: str = "{}"):
        self.output = output

    def generate(self, prompt: str) -> str:
        return self.output


def _num(answer: object) -> float:
    m = re.search(r"[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?", str(answer))
    assert m, f"No number found in answer: {answer!r}"
    return float(m.group(0))


def _answers(problem: str) -> list[object]:
    return [solve_schema(schema).answer for schema in generate_equations_candidate_schemas(problem)]


def test_midpoint_between_opposite_charges_keeps_both_sources():
    problem = (
        "In a vacuum, consider two electric charges q1 = -q2 = 10^-7 C placed at points A and B, "
        "separated by 8 cm. Determine the resultant force acting on electric charge q0 = 10^-7 C "
        "when q0 is placed at H, which is the midpoint of AB."
    )
    assert any(_num(ans) == pytest.approx(1.125e-1, rel=2e-3) for ans in _answers(problem) if ans)


def test_symmetric_midpoint_and_center_zero_rules():
    midpoint = (
        "Two point charges, q1 and q2, of equal magnitude and the same sign, are placed in air a distance r apart. "
        "A third point charge, q3, is placed at the midpoint of the line segment connecting q1 and q2. "
        "What is the net force acting on charge q3?"
    )
    square = (
        "Four identical charges q1, q2, q3, q4 are placed at the four vertices of a square ABCD, "
        "with a side length of 4 cm, respectively. Find the electric force acting on a charge q0 = 2×10^-8 C placed at the center of the square."
    )
    equilateral = (
        "Three identical charges 'q' are placed at the three vertices of an equilateral triangle with side length 'a'. "
        "Find the net electric force acting on a test charge placed at the center of the triangle?"
    )
    alternating_square = (
        "Four charges of the same magnitude q are placed at the four vertices of a square ABCD with side length a. "
        "Positive charges are located at A and C, while negative charges are located at B and D. "
        "Determine the resultant electric field strength at the intersection point of the square's diagonals."
    )
    for problem in [midpoint, square, equilateral, alternating_square]:
        assert any(_num(ans) == pytest.approx(0.0, abs=1e-12) for ans in _answers(problem) if ans)


def test_right_triangle_altitude_foot_force():
    problem = (
        "At the three vertices of right-angled triangle ABC (right-angled at A), with AB = 30 cm, "
        "AC = 40 cm, and BC = 50 cm, charges q1 = q2 = q3 = 10^-9 C are placed. "
        "Determine the magnitude of the net electric force acting on a charge q = 10^-9 C placed at point H, "
        "which is the foot of the altitude from A."
    )
    assert any(_num(ans) == pytest.approx(2.459e-7, rel=5e-3) for ans in _answers(problem) if ans)


def test_equilateral_two_opposite_charges_field_at_equal_distance_point():
    problem = (
        "Two point charges q1 = 2 × 10⁻² μC and q2 = –2 × 10⁻² μC are placed at two points A and B, "
        "separated by a distance a = 30 cm, in air. What is the magnitude of the electric field strength at point M, "
        "which is equidistant from A and B by a distance a = 30 cm?"
    )
    assert any(_num(ans) == pytest.approx(2000.0, rel=2e-3) for ans in _answers(problem) if ans)


def test_square_three_sources_field_at_fourth_vertex():
    problem = (
        "Three equal positive point charges, q = 5 × 10^-9 C, are placed at three vertices of a square with side length a = 40 cm. "
        "What is the magnitude of the electric field at the fourth vertex of the square?"
    )
    assert any(_num(ans) == pytest.approx(538.0, rel=5e-3) for ans in _answers(problem) if ans)


def test_square_center_missing_charge_for_zero_field():
    problem = (
        "At the three vertices A, B, and C of a square ABCD with side length 6 cm in a vacuum, three point charges are placed: "
        "q1 = q3 = 2 × 10^-7 C and q2 = -4 × 10^-7 C. Determine the charge q4 placed at D such that the net electric field strength caused by the system of charges at the center O is zero."
    )
    assert any(_num(ans) == pytest.approx(-4e-7, rel=1e-9) for ans in _answers(problem) if ans)


def test_midpoint_field_from_two_field_values_more_wording():
    problem = (
        "Two points A and B lie on the same electric field line generated by a positive point charge q > 0. "
        "The magnitude of the electric field strength at A is 36 V/m, and at B is 9 V/m. "
        "Determine the electric field strength at M, the midpoint of AB."
    )
    assert any(_num(ans) == pytest.approx(16.0, rel=1e-9) for ans in _answers(problem) if ans)


def test_zero_field_distance_reference_from_m_to_b():
    problem = (
        "Two point charges, q1 = 4 mC and q2 = −9 mC, are placed at points A and B, separated by 9 cm in a vacuum. "
        "What is the distance from point M to B, given that the net electric field at point M is zero?"
    )
    assert any(_num(ans) == pytest.approx(27.0, rel=1e-9) for ans in _answers(problem) if ans)


def test_triangle_distances_field_query_stays_field_not_force():
    problem = (
        "Two electric charges q1 = +3 × 10^-6 C and q2 = +4 × 10^-6 C are placed at points A and B, which are 5 cm apart. "
        "Calculate the resultant electric field strength at point M, which is 3 cm from A and 4 cm from B."
    )
    assert any(str(ans).endswith("V/m") and _num(ans) == pytest.approx(3.75e7, rel=2e-3) for ans in _answers(problem) if ans)


def test_parallel_capacitor_voltage_under_limit_candidate():
    problem = (
        "Two capacitors with capacitances C1 = 0.4μF and C2 = 0.6μF are connected in parallel, and then connected to a power source with a voltage U < 60 V. "
        "One of the two capacitors has a charge of 3 × 10^-5 C. Calculate the voltage U."
    )
    out = solve_problem_with_llm(problem, FakeSchemaLLM("{}"), k=2)
    assert out.solve_result.status == "ok"
    assert _num(out.solve_result.answer) == pytest.approx(50.0, rel=1e-9)


def test_replay_evaluator_supports_kv_per_meter_unit_alias():
    assert compare_answer("389711.431703 V/m", "389", expected_unit="kV/m") is True
