from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable


_BLOCK_SEPARATOR_RE = re.compile(r"^={20,}\s*$", re.MULTILINE)
_HEADER_RE = re.compile(r"\[(?P<ordinal>\d+)/(?:\d+)\]\s+row=(?P<row>\d+)\s+id=(?P<case_id>\S+)")
_FIELD_RE = re.compile(r"^(?P<key>status|domain|answer|expected|expected_unit|correct|elapsed_sec):\s*(?P<value>.*)$", re.MULTILINE)


@dataclass(frozen=True)
class ReplayCacheEntry:
    """A cached schema generated by a previous LLM run."""

    case_id: str
    question: str
    schema: dict[str, Any]
    raw_output: str
    row: int | None = None
    metadata: dict[str, Any] | None = None

    def to_json_obj(self) -> dict[str, Any]:
        return {
            "id": self.case_id,
            "row": self.row,
            "question": self.question,
            "schema": self.schema,
            "raw_output": self.raw_output,
            "metadata": self.metadata or {},
        }

    @classmethod
    def from_json_obj(cls, obj: dict[str, Any]) -> "ReplayCacheEntry":
        case_id = str(obj.get("id") or obj.get("case_id") or "").strip()
        if not case_id:
            raise ValueError(f"Replay cache entry is missing id/case_id: {obj!r}")

        schema = obj.get("schema")
        if not isinstance(schema, dict):
            raw_output = obj.get("raw_output") or obj.get("llm_output")
            if isinstance(raw_output, str):
                schema = json.loads(raw_output)
            else:
                raise ValueError(f"Replay cache entry {case_id} is missing schema/raw_output")

        raw_output = obj.get("raw_output") or obj.get("llm_output")
        if not isinstance(raw_output, str):
            raw_output = json.dumps(schema, ensure_ascii=False)

        row_value = obj.get("row")
        try:
            row = int(row_value) if row_value is not None else None
        except (TypeError, ValueError):
            row = None

        metadata = obj.get("metadata") if isinstance(obj.get("metadata"), dict) else {}
        return cls(
            case_id=case_id,
            question=str(obj.get("question") or ""),
            schema=schema,
            raw_output=raw_output,
            row=row,
            metadata=metadata,
        )


class ReplaySchemaLLM:
    """SchemaLLMClient implementation that replays cached schemas by case id.

    Use ``set_case_id`` before each call to ``generate``. This lets the normal
    schema pipeline run as-is while replacing expensive model generation with a
    previous LLM schema from disk.
    """

    def __init__(self, cache: dict[str, ReplayCacheEntry], *, strict: bool = True):
        self.cache = cache
        self.strict = strict
        self.case_id: str | None = None
        self.last_prompt: str | None = None

    def set_case_id(self, case_id: str) -> None:
        self.case_id = str(case_id)

    def generate_for_case(self, case_id: str, prompt: str = "") -> str:
        self.set_case_id(case_id)
        return self.generate(prompt)

    def generate(self, prompt: str) -> str:
        self.last_prompt = prompt
        if not self.case_id:
            raise ValueError("ReplaySchemaLLM requires set_case_id(case_id) before generate().")

        entry = self.cache.get(self.case_id)
        if entry is None:
            if self.strict:
                raise KeyError(f"No replay schema cached for case id {self.case_id!r}")
            return "{}"

        return entry.raw_output


def _parse_result_metadata(block: str) -> dict[str, Any]:
    metadata: dict[str, Any] = {}
    result_section = _section_between(block, "RESULT:\n", ["\n\nCHECK DEBUG:", "\n\nERROR:", "\n\nSCHEMA:"])
    if result_section is None:
        result_section = block
    for match in _FIELD_RE.finditer(result_section):
        key = match.group("key")
        value: Any = match.group("value").strip()
        if key == "correct":
            if value.lower() == "true":
                value = True
            elif value.lower() == "false":
                value = False
        elif key == "elapsed_sec":
            try:
                value = float(value)
            except ValueError:
                pass
        metadata[key] = value
    return metadata


def _section_between(block: str, start_marker: str, end_markers: Iterable[str]) -> str | None:
    start = block.find(start_marker)
    if start < 0:
        return None
    start += len(start_marker)

    end_positions = [block.find(marker, start) for marker in end_markers]
    end_positions = [pos for pos in end_positions if pos >= 0]
    end = min(end_positions) if end_positions else len(block)
    return block[start:end].strip()


def _extract_json_object(text: str) -> dict[str, Any]:
    decoder = json.JSONDecoder()
    stripped = text.strip()
    obj, _ = decoder.raw_decode(stripped)
    if not isinstance(obj, dict):
        raise ValueError("Expected schema JSON object")
    return obj


def parse_eval_log(text: str) -> list[ReplayCacheEntry]:
    """Parse the text log produced by the dataset LLM benchmark.

    Expected blocks look like ``[1/500] row=100 id=TD009`` followed by QUESTION,
    RESULT, SCHEMA and RUNNING SUMMARY sections. Unknown sections are ignored.
    """

    entries: list[ReplayCacheEntry] = []
    seen: set[str] = set()

    for block in _BLOCK_SEPARATOR_RE.split(text):
        header = _HEADER_RE.search(block)
        if header is None:
            continue

        case_id = header.group("case_id")
        if case_id in seen:
            continue

        question = _section_between(block, "QUESTION:\n", ["\n\nRESULT:"])
        schema_text = _section_between(block, "SCHEMA:\n", ["\n\nRUNNING SUMMARY:"])
        if not question or not schema_text:
            continue

        try:
            schema = _extract_json_object(schema_text)
        except (json.JSONDecodeError, ValueError):
            continue

        metadata = _parse_result_metadata(block)
        row = int(header.group("row"))
        raw_output = json.dumps(schema, ensure_ascii=False)
        entries.append(
            ReplayCacheEntry(
                case_id=case_id,
                question=question,
                schema=schema,
                raw_output=raw_output,
                row=row,
                metadata=metadata,
            )
        )
        seen.add(case_id)

    return entries


def load_replay_cache(path: str | Path) -> dict[str, ReplayCacheEntry]:
    path = Path(path)
    cache: dict[str, ReplayCacheEntry] = {}

    with path.open("r", encoding="utf-8-sig") as f:
        first = f.read(1)
        f.seek(0)
        if first == "[":
            data = json.load(f)
            if not isinstance(data, list):
                raise ValueError("Replay cache JSON must be a list or JSONL file")
            objects = data
        else:
            objects = [json.loads(line) for line in f if line.strip()]

    for obj in objects:
        if not isinstance(obj, dict):
            continue
        entry = ReplayCacheEntry.from_json_obj(obj)
        cache[entry.case_id] = entry

    return cache


def write_replay_cache(entries: Iterable[ReplayCacheEntry], path: str | Path) -> int:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    count = 0
    with path.open("w", encoding="utf-8") as f:
        for entry in entries:
            f.write(json.dumps(entry.to_json_obj(), ensure_ascii=False, sort_keys=True))
            f.write("\n")
            count += 1
    return count
