from __future__ import annotations

from typing import Any

from .types import FormulaDoc


def _schema(formula_name: str, objects: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "domain": "equations",
        "objects": objects,
        "relations": [
            {
                "type": "formula",
                "name": formula_name,
                "objects": [obj["id"] for obj in objects],
            }
        ],
        "constraints": [],
    }


FORMULA_DOCS: list[FormulaDoc] = [
    FormulaDoc(
        id="capacitor_energy_voltage",
        name="Capacitor energy from capacitance and voltage",
        equation="W = 1/2 C U^2",
        description="Use for scalar capacitor energy when capacitance and voltage are known.",
        quantity_types=["energy", "capacitance", "voltage"],
        query_types=["energy", "capacitance", "voltage"],
        tags=["capacitor", "energy", "voltage", "capacitance"],
        keywords=["stored energy", "energy stored", "capacitor energy", "C and U", "capacitance voltage"],
        schema_template=_schema(
            "capacitor_energy_voltage",
            [
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF|nF|pF>"},
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "<V|kV|mV>"},
                {"id": "W_query", "type": "energy", "role": "query", "value": None, "unit": "<J|mJ|uJ>"},
            ],
        ),
    ),
    FormulaDoc(
        id="capacitor_charge_voltage",
        name="Capacitor charge-voltage relation",
        equation="Q = C U",
        description="Use for direct scalar relation among charge, capacitance, and voltage.",
        quantity_types=["charge", "capacitance", "voltage"],
        query_types=["charge", "capacitance", "voltage"],
        tags=["capacitor", "charge", "voltage", "capacitance"],
        keywords=["charge on capacitor", "potential difference", "Q equals C U", "find charge", "find voltage"],
        schema_template=_schema(
            "capacitor_charge_voltage",
            [
                {"id": "Q_query", "type": "charge", "role": "query", "value": None, "unit": "<C|mC|uC|nC>"},
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF|nF|pF>"},
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "<V|kV|mV>"},
            ],
        ),
    ),
    FormulaDoc(
        id="parallel_plate_capacitance",
        name="Parallel-plate capacitance",
        equation="C = eps0 eps_r A / d",
        description="Use for capacitance of a parallel-plate capacitor from area, separation, and dielectric constant.",
        quantity_types=["capacitance", "area", "distance", "relative_permittivity"],
        query_types=["capacitance", "relative_permittivity", "area", "distance"],
        tags=["capacitor", "parallel_plate", "capacitance", "area", "distance", "dielectric"],
        keywords=["parallel plate", "plate area", "plate separation", "air capacitor", "dielectric constant"],
        schema_template=_schema(
            "parallel_plate_capacitance",
            [
                {"id": "A1", "type": "area", "role": "given", "value": "<number>", "unit": "<m2|cm2|mm2>"},
                {"id": "d1", "type": "distance", "role": "given", "value": "<number>", "unit": "<m|cm|mm>"},
                {"id": "C_query", "type": "capacitance", "role": "query", "value": None, "unit": "<F|uF|nF|pF>"},
            ],
        ),
    ),
    FormulaDoc(
        id="series_capacitance_unknown",
        name="Two capacitors in series, unknown capacitance",
        equation="1/Ceq = 1/C1 + 1/C2",
        description="Use when equivalent capacitance of two series capacitors is known and one capacitance is unknown.",
        quantity_types=["capacitance"],
        query_types=["capacitance"],
        tags=["capacitor", "series", "equivalent_capacitance", "algebra"],
        keywords=["series capacitors", "connected in series", "equivalent capacitance", "unknown capacitance"],
        schema_template=_schema(
            "series_capacitance_unknown",
            [
                {"id": "Ceq", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF|nF|pF>", "symbol": "Ceq"},
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF|nF|pF>", "symbol": "C1"},
                {"id": "C2_query", "type": "capacitance", "role": "query", "value": None, "unit": "<F|uF|nF|pF>", "symbol": "C2"},
            ],
        ),
    ),
    FormulaDoc(
        id="lc_resonance_frequency",
        name="LC resonance frequency",
        equation="f = 1/(2*pi*sqrt(L*C))",
        description="Use for natural/resonant frequency of an LC circuit from inductance and capacitance.",
        quantity_types=["frequency", "inductance", "capacitance"],
        query_types=["frequency", "inductance", "capacitance"],
        tags=["lc", "resonance", "frequency", "inductance", "capacitance"],
        keywords=["resonance frequency", "resonant frequency", "natural frequency", "LC circuit", "oscillating circuit"],
        schema_template=_schema(
            "lc_resonance_frequency",
            [
                {"id": "L1", "type": "inductance", "role": "given", "value": "<number>", "unit": "<H|mH|uH>"},
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF|nF|pF>"},
                {"id": "f_query", "type": "frequency", "role": "query", "value": None, "unit": "<Hz|kHz>"},
            ],
        ),
    ),
    FormulaDoc(
        id="ohm_law",
        name="Ohm law",
        equation="U = I R",
        description="Use for scalar voltage-current-resistance relation, including resonance when impedance equals resistance.",
        quantity_types=["voltage", "current", "resistance"],
        query_types=["voltage", "current", "resistance"],
        tags=["circuit", "ohm", "voltage", "current", "resistance"],
        keywords=["ohm law", "current through resistor", "voltage resistance current", "at resonance impedance equals resistance"],
        schema_template=_schema(
            "ohm_law",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "<V|kV|mV>"},
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "<?|ohm>"},
                {"id": "I_query", "type": "current", "role": "query", "value": None, "unit": "<A|mA>"},
            ],
        ),
    ),
    FormulaDoc(
        id="parallel_branch_current",
        name="Branch current in a parallel circuit",
        equation="I_i = U/R_i",
        description="Use for current through one lamp/resistor branch connected in parallel. Each branch has the source voltage.",
        quantity_types=["voltage", "resistance", "current", "branch_current"],
        query_types=["current", "branch_current"],
        tags=["circuit", "parallel", "branch", "lamp", "current"],
        keywords=["parallel lamps current", "current through each lamp", "branch current", "same voltage in parallel"],
        schema_template=_schema(
            "parallel_branch_current",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "I1_query", "type": "current", "role": "query", "value": None, "unit": "A"},
            ],
        ),
    ),
    FormulaDoc(
        id="parallel_total_current",
        name="Total current in a parallel circuit",
        equation="I_total = sum(U/R_i)",
        description="Use for total current supplied to parallel branches from source voltage and branch resistances.",
        quantity_types=["voltage", "resistance", "current", "total_current"],
        query_types=["current", "total_current"],
        tags=["circuit", "parallel", "branch", "lamp", "total_current"],
        keywords=["parallel lamps total current", "main current", "current supplied", "sum of branch currents"],
        schema_template=_schema(
            "parallel_total_current",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "R2", "type": "resistance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "Itotal_query", "type": "total_current", "role": "query", "value": None, "unit": "A"},
            ],
        ),
    ),
    FormulaDoc(
        id="parallel_branch_power",
        name="Branch power in a parallel circuit",
        equation="P_i = U^2/R_i",
        description="Use for power consumed by one lamp/resistor branch connected in parallel.",
        quantity_types=["voltage", "resistance", "power", "branch_power"],
        query_types=["power", "branch_power"],
        tags=["circuit", "parallel", "branch", "lamp", "power"],
        keywords=["parallel lamps power", "power of each lamp", "branch power", "power dissipated by branch"],
        schema_template=_schema(
            "parallel_branch_power",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "P1_query", "type": "power", "role": "query", "value": None, "unit": "W"},
            ],
        ),
    ),
    FormulaDoc(
        id="parallel_total_power",
        name="Total power in a parallel circuit",
        equation="P_total = sum(U^2/R_i)",
        description="Use for total power consumed by parallel lamps/resistor branches.",
        quantity_types=["voltage", "resistance", "power", "total_power"],
        query_types=["power", "total_power"],
        tags=["circuit", "parallel", "branch", "lamp", "total_power"],
        keywords=["parallel lamps total power", "total power consumed", "combined power", "sum of branch powers"],
        schema_template=_schema(
            "parallel_total_power",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "R2", "type": "resistance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "Ptotal_query", "type": "total_power", "role": "query", "value": None, "unit": "W"},
            ],
        ),
    ),
    FormulaDoc(
        id="quality_factor",
        name="Series RLC quality factor",
        equation="Q = sqrt(L/C)/R",
        description="Use for quality factor of a series RLC circuit from L, C, and R.",
        quantity_types=["quality_factor", "inductance", "capacitance", "resistance"],
        query_types=["quality_factor"],
        tags=["rlc", "quality_factor", "inductance", "capacitance", "resistance"],
        keywords=["quality factor", "Q factor", "series RLC", "sqrt L over C divided by R"],
        schema_template=_schema(
            "quality_factor",
            [
                {"id": "L1", "type": "inductance", "role": "given", "value": "<number>", "unit": "<H|mH|uH>"},
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF|nF|pF>"},
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "<?|ohm>"},
                {"id": "Q_query", "type": "quality_factor", "role": "query", "value": None, "unit": "-"},
            ],
        ),
    ),
    FormulaDoc(
        id="solenoid_magnetic_field",
        name="Magnetic field inside a long solenoid",
        equation="B = mu0*N*I/l = mu0*n*I",
        description="Use for magnetic field in a long solenoid from turn count or turn density and current.",
        quantity_types=["magnetic_field", "turn_count", "turn_density", "current", "length"],
        query_types=["magnetic_field", "current"],
        tags=["solenoid", "magnetic_field", "turns", "current", "length"],
        keywords=["solenoid", "magnetic field", "number of turns", "turn density", "inside a solenoid"],
        schema_template=_schema(
            "solenoid_magnetic_field",
            [
                {"id": "N1", "type": "turn_count", "role": "given", "value": "<number>", "unit": "turns"},
                {"id": "I1", "type": "current", "role": "given", "value": "<number>", "unit": "<A|mA>"},
                {"id": "l1", "type": "length", "role": "given", "value": "<number>", "unit": "<m|cm>"},
                {"id": "B_query", "type": "magnetic_field", "role": "query", "value": None, "unit": "<T|mT>"},
            ],
        ),
    ),
    FormulaDoc(
        id="solenoid_turn_density",
        name="Solenoid turn density",
        equation="n = N/l",
        description="Use for number of turns per meter, total turns, or solenoid length.",
        quantity_types=["turn_density", "turn_count", "length"],
        query_types=["turn_density", "turn_count", "length"],
        tags=["solenoid", "turn_density", "turns", "length"],
        keywords=["turn density", "turns per meter", "number of turns per meter", "N over length", "turns per unit length"],
        schema_template=_schema(
            "solenoid_turn_density",
            [
                {"id": "N1", "type": "turn_count", "role": "given", "value": "<number>", "unit": "turns"},
                {"id": "l1", "type": "length", "role": "given", "value": "<number>", "unit": "<m|cm>"},
                {"id": "n_query", "type": "turn_density", "role": "query", "value": None, "unit": "turns/m"},
            ],
        ),
    ),
    FormulaDoc(
        id="solenoid_inductance",
        name="Ideal solenoid inductance",
        equation="L = mu0*N^2*A/l",
        description="Use for inductance of a long solenoid from turn count, cross-sectional area, and length.",
        quantity_types=["inductance", "turn_count", "area", "length"],
        query_types=["inductance"],
        tags=["solenoid", "inductance", "turns", "area", "length"],
        keywords=["inductance of solenoid", "solenoid inductance", "cross-sectional area", "mu0 N squared A over length"],
        schema_template=_schema(
            "solenoid_inductance",
            [
                {"id": "N1", "type": "turn_count", "role": "given", "value": "<number>", "unit": "turns"},
                {"id": "A1", "type": "area", "role": "given", "value": "<number>", "unit": "<m2|cm2>"},
                {"id": "l1", "type": "length", "role": "given", "value": "<number>", "unit": "<m|cm>"},
                {"id": "L_query", "type": "inductance", "role": "query", "value": None, "unit": "<H|mH>"},
            ],
        ),
    ),
    FormulaDoc(
        id="point_charge_electric_field",
        name="Electric field of a point charge",
        equation="E = k|q|/(eps_r*r^2)",
        description="Use for scalar electric field magnitude due to one point charge at a distance.",
        quantity_types=["electric_field", "charge", "distance", "relative_permittivity"],
        query_types=["electric_field"],
        tags=["electric_field", "point_charge", "charge", "distance"],
        keywords=["electric field due to point charge", "field at distance", "point charge electric field"],
        schema_template=_schema(
            "point_charge_electric_field",
            [
                {"id": "q1", "type": "charge", "role": "given", "value": "<number>", "unit": "<C|mC|uC|nC>"},
                {"id": "r1", "type": "distance", "role": "given", "value": "<number>", "unit": "<m|cm|mm>"},
                {"id": "E_query", "type": "electric_field", "role": "query", "value": None, "unit": "<V/m|N/C>"},
            ],
        ),
    ),
    FormulaDoc(
        id="percentage_relative_error",
        name="Percentage relative error",
        equation="percent_error = absolute_error/measured_value * 100%",
        description="Use when the problem asks for percentage relative error from absolute error and measured value.",
        quantity_types=["percent_error", "absolute_error", "measured_value"],
        query_types=["percent_error"],
        tags=["measurement_error", "relative_error", "percentage", "uncertainty"],
        keywords=["percentage error", "relative error", "absolute error", "absolute uncertainty", "least count", "measured value", "percentage relative uncertainty"],
        schema_template=_schema(
            "percentage_relative_error",
            [
                {"id": "err1", "type": "absolute_error", "role": "given", "value": "<number>", "unit": "<same as measured or blank>"},
                {"id": "measured1", "type": "measured_value", "role": "given", "value": "<number>", "unit": "<unit or blank>"},
                {"id": "percent_query", "type": "percent_error", "role": "query", "value": None, "unit": "%"},
            ],
        ),
    ),
    FormulaDoc(
        id="harmonic_current_cos_time",
        name="Sinusoidal current at time t",
        equation="i(t) = I0*cos(omega*t + phi)",
        description="Use for instantaneous harmonic current from amplitude, angular frequency, time, and optional phase.",
        quantity_types=["current", "current_amplitude", "angular_frequency", "time", "phase"],
        query_types=["current"],
        tags=["sinusoidal", "time_domain", "current", "angular_frequency"],
        keywords=["instantaneous current", "cos omega t", "sinusoidal current", "current at time"],
        schema_template=_schema(
            "harmonic_current_cos_time",
            [
                {"id": "I0", "type": "current_amplitude", "role": "given", "value": "<number>", "unit": "<A|mA>"},
                {"id": "omega1", "type": "angular_frequency", "role": "given", "value": "<number>", "unit": "rad/s"},
                {"id": "t1", "type": "time", "role": "given", "value": "<number>", "unit": "<s|ms>"},
                {"id": "I_query", "type": "current", "role": "query", "value": None, "unit": "<A|mA>"},
            ],
        ),
    ),    FormulaDoc(
        id="parallel_plate_field",
        name="Electric field between parallel plates",
        equation="E = U/d",
        description="Use for uniform electric field between capacitor plates from voltage and plate separation.",
        quantity_types=["electric_field", "voltage", "distance"],
        query_types=["electric_field", "voltage", "distance"],
        tags=["capacitor", "parallel_plate", "electric_field", "voltage", "distance"],
        keywords=["electric field between plates", "field in capacitor", "E equals U over d", "plate separation"],
        schema_template=_schema(
            "parallel_plate_field",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "<V|kV|mV>"},
                {"id": "d1", "type": "distance", "role": "given", "value": "<number>", "unit": "<m|cm|mm>"},
                {"id": "E_query", "type": "electric_field", "role": "query", "value": None, "unit": "<V/m|kV/m>"},
            ],
        ),
    ),
    FormulaDoc(
        id="capacitor_energy_density",
        name="Electric energy density in capacitor field",
        equation="u = 1/2 eps0 eps_r E^2 = 1/2 eps0 eps_r (U/d)^2",
        description="Use for energy density between capacitor plates from electric field or voltage and distance.",
        quantity_types=["energy_density", "electric_field", "voltage", "distance", "relative_permittivity"],
        query_types=["energy_density"],
        tags=["capacitor", "energy_density", "electric_field", "voltage", "distance"],
        keywords=["energy density", "electric field energy density", "between plates", "capacitor energy density"],
        schema_template=_schema(
            "capacitor_energy_density",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "<V|kV|mV>"},
                {"id": "d1", "type": "distance", "role": "given", "value": "<number>", "unit": "<m|cm|mm>"},
                {"id": "u_query", "type": "energy_density", "role": "query", "value": None, "unit": "<J/m3>"},
            ],
        ),
    ),
    FormulaDoc(
        id="capacitor_energy_scaling_constant_voltage",
        name="Capacitor energy scaling at constant voltage",
        equation="W2/W1 = C2/C1",
        description="Use when capacitor voltage is constant and capacitance changes by a factor.",
        quantity_types=["ratio"],
        query_types=["ratio"],
        tags=["capacitor", "energy", "scaling", "constant_voltage", "capacitance"],
        keywords=["constant voltage", "voltage remains constant", "capacitance doubled", "energy changes by factor"],
        schema_template=_schema(
            "capacitor_energy_scaling_constant_voltage",
            [
                {"id": "C_ratio", "type": "ratio", "role": "given", "value": "<number>", "unit": "times", "symbol": "C2/C1"},
                {"id": "W_ratio_query", "type": "ratio", "role": "query", "value": None, "unit": "times", "symbol": "W2/W1"},
            ],
        ),
    ),
    FormulaDoc(
        id="capacitor_energy_voltage_scaling_constant_capacitance",
        name="Capacitor energy scaling at constant capacitance from voltage ratio",
        equation="W2/W1 = (U2/U1)^2",
        description="Use when capacitance is constant and voltage changes by a factor.",
        quantity_types=["ratio"],
        query_types=["ratio"],
        tags=["capacitor", "energy", "scaling", "constant_capacitance", "voltage"],
        keywords=["constant capacitance", "voltage doubled", "voltage tripled", "energy proportional to voltage squared"],
        schema_template=_schema(
            "capacitor_energy_voltage_scaling_constant_capacitance",
            [
                {"id": "U_ratio", "type": "ratio", "role": "given", "value": "<number>", "unit": "times", "symbol": "U2/U1"},
                {"id": "W_ratio_query", "type": "ratio", "role": "query", "value": None, "unit": "times", "symbol": "W2/W1"},
            ],
        ),
    ),
    FormulaDoc(
        id="inductor_energy",
        name="Energy stored in an inductor",
        equation="W = 1/2 L I^2",
        description="Use for magnetic energy stored in an inductor from inductance and current.",
        quantity_types=["energy", "inductance", "current"],
        query_types=["energy", "inductance", "current"],
        tags=["inductor", "energy", "inductance", "current"],
        keywords=["energy stored in inductor", "magnetic energy", "inductance current"],
        schema_template=_schema(
            "inductor_energy",
            [
                {"id": "L1", "type": "inductance", "role": "given", "value": "<number>", "unit": "<H|mH|uH>"},
                {"id": "I1", "type": "current", "role": "given", "value": "<number>", "unit": "<A|mA>"},
                {"id": "W_query", "type": "energy", "role": "query", "value": None, "unit": "<J|mJ>"},
            ],
        ),
    ),
    FormulaDoc(
        id="ac_impedance",
        name="Series AC impedance",
        equation="Z = sqrt(R^2 + (XL - XC)^2)",
        description="Use for impedance magnitude of a series AC/RLC circuit from R, XL, and XC.",
        quantity_types=["impedance", "resistance", "inductive_reactance", "capacitive_reactance"],
        query_types=["impedance"],
        tags=["ac", "rlc", "impedance", "resistance", "reactance"],
        keywords=["impedance", "reactance", "inductive reactance", "capacitive reactance", "series AC"],
        schema_template=_schema(
            "ac_impedance",
            [
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "<?|ohm>"},
                {"id": "XL1", "type": "inductive_reactance", "role": "given", "value": "<number>", "unit": "<?|ohm>"},
                {"id": "XC1", "type": "capacitive_reactance", "role": "given", "value": "<number>", "unit": "<?|ohm>"},
                {"id": "Z_query", "type": "impedance", "role": "query", "value": None, "unit": "<?|ohm>"},
            ],
        ),
    ),
    FormulaDoc(
        id="power_voltage_resistance",
        name="Power from voltage and resistance",
        equation="P = U^2/R",
        description="Use for electric power consumed by a resistor from voltage and resistance.",
        quantity_types=["power", "voltage", "resistance"],
        query_types=["power", "voltage", "resistance"],
        tags=["power", "voltage", "resistance", "circuit"],
        keywords=["power consumed", "voltage and resistance", "P equals U squared over R"],
        schema_template=_schema(
            "power_voltage_resistance",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "<V|kV|mV>"},
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "<?|ohm>"},
                {"id": "P_query", "type": "power", "role": "query", "value": None, "unit": "<W|mW>"},
            ],
        ),
    ),
    FormulaDoc(
        id="magnetic_flux",
        name="Magnetic flux through one turn or cross-section",
        equation="Phi = B*A",
        description="Use for magnetic flux through one turn, each turn, one loop, or a cross-sectional area. If B is not given but solenoid turn density/current are given, first use B = mu0*n*I.",
        quantity_types=["magnetic_flux", "magnetic_field", "area", "turn_density", "turn_count", "length", "current"],
        query_types=["magnetic_flux"],
        tags=["magnetic_flux", "magnetic_field", "area", "solenoid", "one_turn"],
        keywords=["magnetic flux through one turn", "flux through each turn", "flux through cross-section", "flux through this area", "B A", "magnetic flux"],
        schema_template=_schema(
            "magnetic_flux",
            [
                {"id": "B1", "type": "magnetic_field", "role": "given", "value": "<number>", "unit": "<T|mT>"},
                {"id": "A1", "type": "area", "role": "given", "value": "<number>", "unit": "<m2|cm2>"},
                {"id": "Phi_query", "type": "magnetic_flux", "role": "query", "value": None, "unit": "<Wb|mWb|uWb>"},
            ],
        ),
    ),
    FormulaDoc(
        id="magnetic_flux_linkage",
        name="Total magnetic flux linkage",
        equation="lambda = N*Phi = N*B*A",
        description="Use for total flux linkage through a coil from flux per turn and number of turns, or from B, area, and turn count.",
        quantity_types=["magnetic_flux_linkage", "magnetic_flux", "turn_count", "magnetic_field", "area"],
        query_types=["magnetic_flux_linkage", "magnetic_flux"],
        tags=["magnetic_flux", "flux_linkage", "turns", "coil"],
        keywords=["flux linkage", "total magnetic flux linkage", "total flux", "N Phi", "N B A"],
        schema_template=_schema(
            "magnetic_flux_linkage",
            [
                {"id": "N1", "type": "turn_count", "role": "given", "value": "<number>", "unit": "turns"},
                {"id": "Phi1", "type": "magnetic_flux", "role": "given", "value": "<number>", "unit": "<Wb|mWb|uWb>"},
                {"id": "Lambda_query", "type": "magnetic_flux_linkage", "role": "query", "value": None, "unit": "<Wb|mWb|uWb>"},
            ],
        ),
    ),
    FormulaDoc(
        id="magnetic_energy_density",
        name="Magnetic field energy density",
        equation="u = B^2/(2*mu0)",
        description="Use for magnetic energy density from magnetic field B. For a solenoid, B may be computed from turn density and current.",
        quantity_types=["energy_density", "magnetic_field", "turn_density", "current", "turn_count", "length"],
        query_types=["energy_density"],
        tags=["magnetic_field", "energy_density", "solenoid"],
        keywords=["magnetic energy density", "magnetic field energy density", "energy density inside solenoid", "B squared over 2 mu0"],
        schema_template=_schema(
            "magnetic_energy_density",
            [
                {"id": "B1", "type": "magnetic_field", "role": "given", "value": "<number>", "unit": "<T|mT>"},
                {"id": "u_query", "type": "energy_density", "role": "query", "value": None, "unit": "<J/m3>"},
            ],
        ),
    ),
    FormulaDoc(
        id="magnetic_flux_total",
        name="Magnetic flux through one or multiple turns",
        equation="Phi = N B A",
        description="Use for magnetic flux linkage from magnetic field, area, and optional turn count.",
        quantity_types=["magnetic_flux", "turn_count", "magnetic_field", "area"],
        query_types=["magnetic_flux"],
        tags=["magnetic_flux", "magnetic_field", "area", "turns"],
        keywords=["magnetic flux", "flux through coil", "flux linkage", "B A", "N B A"],
        schema_template=_schema(
            "magnetic_flux_total",
            [
                {"id": "N1", "type": "turn_count", "role": "given", "value": "<number>", "unit": "turns"},
                {"id": "B1", "type": "magnetic_field", "role": "given", "value": "<number>", "unit": "<T|mT>"},
                {"id": "A1", "type": "area", "role": "given", "value": "<number>", "unit": "<m2|cm2>"},
                {"id": "Phi_query", "type": "magnetic_flux", "role": "query", "value": None, "unit": "<Wb|mWb|uWb>"},
            ],
        ),
    ),
    FormulaDoc(
        id="absolute_error_from_actual",
        name="Absolute error from measured and actual value",
        equation="absolute_error = |actual - measured|",
        description="Use when the problem gives actual and measured values and asks for absolute error.",
        quantity_types=["absolute_error", "actual_value", "measured_value"],
        query_types=["absolute_error"],
        tags=["measurement_error", "absolute_error"],
        keywords=["absolute error", "actual value", "measured value", "measurement error"],
        schema_template=_schema(
            "absolute_error_from_actual",
            [
                {"id": "actual1", "type": "actual_value", "role": "given", "value": "<number>", "unit": "<unit or blank>"},
                {"id": "measured1", "type": "measured_value", "role": "given", "value": "<number>", "unit": "<unit or blank>"},
                {"id": "err_query", "type": "absolute_error", "role": "query", "value": None, "unit": "<same unit or blank>"},
            ],
        ),
    ),
    FormulaDoc(
        id="lc_electric_energy_time",
        name="LC electric energy at time t",
        equation="We = Wtotal*cos^2(omega*t + phi)",
        description="Use for electric-field energy in an LC oscillator at a given time.",
        quantity_types=["energy", "angular_frequency", "time", "phase"],
        query_types=["energy"],
        tags=["lc", "energy", "time_domain", "angular_frequency"],
        keywords=["LC electric energy at time", "cos squared", "energy at time", "omega t"],
        schema_template=_schema(
            "lc_electric_energy_time",
            [
                {"id": "W_total", "type": "energy", "role": "given", "value": "<number>", "unit": "<J|mJ|uJ>"},
                {"id": "omega1", "type": "angular_frequency", "role": "given", "value": "<number>", "unit": "rad/s"},
                {"id": "t1", "type": "time", "role": "given", "value": "<number>", "unit": "<s|ms>"},
                {"id": "We_query", "type": "energy", "role": "query", "value": None, "unit": "<J|mJ|uJ>"},
            ],
        ),
    ),

    FormulaDoc(
        id="capacitor_energy_charge_voltage",
        name="Capacitor energy from charge and voltage",
        equation="W = 1/2 Q U",
        description="Use for scalar capacitor energy when charge and voltage are known.",
        quantity_types=["energy", "charge", "voltage"],
        query_types=["energy", "charge", "voltage"],
        tags=["capacitor", "energy", "charge", "voltage"],
        keywords=["energy stored", "charge and voltage", "electric field energy", "half Q U"],
        schema_template=_schema(
            "capacitor_energy_charge_voltage",
            [
                {"id": "Q1", "type": "charge", "role": "given", "value": "<number>", "unit": "<C|mC|uC|nC>"},
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "<V|kV|mV>"},
                {"id": "W_query", "type": "energy", "role": "query", "value": None, "unit": "<J|mJ|uJ>"},
            ],
        ),
    ),
    FormulaDoc(
        id="capacitor_energy_charge_capacitance",
        name="Capacitor energy from charge and capacitance",
        equation="W = Q^2/(2 C)",
        description="Use for scalar capacitor energy when charge and capacitance are known, or inverse queries for charge/capacitance from energy.",
        quantity_types=["energy", "charge", "capacitance"],
        query_types=["energy", "charge", "capacitance"],
        tags=["capacitor", "energy", "charge", "capacitance"],
        keywords=[
            "energy stored",
            "electric field energy",
            "charge and capacitance",
            "given charge and capacitance",
            "Q squared over 2C",
            "Q^2/(2C)",
            "without voltage",
        ],
        schema_template=_schema(
            "capacitor_energy_charge_capacitance",
            [
                {"id": "Q1", "type": "charge", "role": "given", "value": "<number>", "unit": "<C|mC|uC|nC>"},
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF|nF|pF>"},
                {"id": "W_query", "type": "energy", "role": "query", "value": None, "unit": "<J|mJ|uJ>"},
            ],
        ),
    ),
    FormulaDoc(
        id="parallel_plate_capacitance_distance_scaling",
        name="Parallel-plate capacitance scaling from plate separation",
        equation="C2/C1 = d1/d2",
        description="Use when initial capacitance is known and plate separation is scaled while area and medium stay fixed.",
        quantity_types=["capacitance", "ratio"],
        query_types=["capacitance"],
        tags=["capacitor", "parallel_plate", "capacitance", "distance_scaling"],
        keywords=["distance halved", "distance doubled", "plate separation halved", "new capacitance"],
        schema_template=_schema(
            "parallel_plate_capacitance_distance_scaling",
            [
                {"id": "C_initial", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF|nF|pF>", "symbol": "C1"},
                {"id": "d_ratio", "type": "ratio", "role": "given", "value": "<number>", "unit": "times", "symbol": "d2/d1"},
                {"id": "C_query", "type": "capacitance", "role": "query", "value": None, "unit": "<F|uF|nF|pF>", "symbol": "C2"},
            ],
        ),
    ),
    FormulaDoc(
        id="capacitor_plate_force_by_charge_area",
        name="Attractive force between capacitor plates from charge and area",
        equation="F = Q^2/(2 eps0 eps_r A)",
        description="Use for electrostatic attractive force between parallel capacitor plates when charge and plate area are known.",
        quantity_types=["force", "charge", "area", "relative_permittivity"],
        query_types=["force"],
        tags=["capacitor", "parallel_plate", "force", "charge", "area"],
        keywords=["attractive force between plates", "force between capacitor plates", "charge and area"],
        schema_template=_schema(
            "capacitor_plate_force_by_charge_area",
            [
                {"id": "Q1", "type": "charge", "role": "given", "value": "<number>", "unit": "<C|mC|uC>"},
                {"id": "A1", "type": "area", "role": "given", "value": "<number>", "unit": "<m2|cm2>"},
                {"id": "F_query", "type": "force", "role": "query", "value": None, "unit": "<N|mN>"},
            ],
        ),
    ),
    FormulaDoc(
        id="instrument_absolute_error",
        name="Instrument absolute error from least count",
        equation="Delta x = least count",
        description="Use when an instrument least count is given and the question asks for absolute measurement error.",
        quantity_types=["absolute_error", "least_count", "measured_value"],
        query_types=["absolute_error"],
        tags=["measurement_error", "absolute_error", "least_count", "instrument"],
        keywords=["least count", "absolute error", "ammeter", "voltmeter", "instrument"],
        schema_template=_schema(
            "instrument_absolute_error",
            [
                {"id": "least_count1", "type": "least_count", "role": "given", "value": "<number>", "unit": "<unit>"},
                {"id": "err_query", "type": "absolute_error", "role": "query", "value": None, "unit": "<same unit>"},
            ],
        ),
    ),
    FormulaDoc(
        id="measurement_average",
        name="Average value and average absolute error from repeated measurements",
        equation="xbar = mean(x_i), Delta = mean(|x_i-xbar|)",
        description="Use for repeated measurements asking average value, average absolute error, or relative error.",
        quantity_types=["measured_value", "average_value", "average_absolute_error", "relative_error"],
        query_types=["average_value", "average_absolute_error", "relative_error"],
        tags=["measurement_error", "average_value", "average_absolute_error", "repeated_measurements"],
        keywords=["average value", "average absolute error", "repeated measurements", "mean measurement"],
        schema_template=_schema(
            "measurement_average",
            [
                {"id": "x1", "type": "measured_value", "role": "given", "value": "<number>", "unit": "<unit>"},
                {"id": "x2", "type": "measured_value", "role": "given", "value": "<number>", "unit": "<unit>"},
                {"id": "mean_query", "type": "average_value", "role": "query", "value": None, "unit": "<unit>"},
                {"id": "err_query", "type": "average_absolute_error", "role": "query", "value": None, "unit": "<unit>"},
            ],
        ),
    ),
    FormulaDoc(
        id="random_error_half_range",
        name="Random error from half range",
        equation="Delta_random = (max(x_i)-min(x_i))/2",
        description="Use for repeated measurements when the question asks random error, not average absolute error.",
        quantity_types=["measured_value", "random_error"],
        query_types=["random_error", "absolute_error"],
        tags=["measurement_error", "random_error", "repeated_measurements"],
        keywords=["random error", "half range", "maximum minus minimum", "three measurements"],
        schema_template=_schema(
            "random_error_half_range",
            [
                {"id": "x1", "type": "measured_value", "role": "given", "value": "<number>", "unit": "<unit>"},
                {"id": "x2", "type": "measured_value", "role": "given", "value": "<number>", "unit": "<unit>"},
                {"id": "x3", "type": "measured_value", "role": "given", "value": "<number>", "unit": "<unit>"},
                {"id": "err_query", "type": "random_error", "role": "query", "value": None, "unit": "<unit>"},
            ],
        ),
    ),
    FormulaDoc(
        id="measurement_maximum",
        name="Maximum possible measured value",
        equation="x_max = x_measured + Delta x",
        description="Use when a measurement is given with an uncertainty and the question asks maximum possible value.",
        quantity_types=["measured_value", "absolute_error", "uncertainty", "maximum_value"],
        query_types=["maximum_value"],
        tags=["measurement_error", "uncertainty", "maximum_value"],
        keywords=["maximum possible", "maximum value", "measured plus uncertainty", "uncertainty"],
        schema_template=_schema(
            "measurement_maximum",
            [
                {"id": "x1", "type": "measured_value", "role": "given", "value": "<number>", "unit": "<unit>"},
                {"id": "dx1", "type": "absolute_error", "role": "given", "value": "<number>", "unit": "<unit>"},
                {"id": "max_query", "type": "maximum_value", "role": "query", "value": None, "unit": "<unit>"},
            ],
        ),
    ),
    FormulaDoc(
        id="resistance_uncertainty_quotient",
        name="Uncertainty propagation for R = U/I",
        equation="DeltaR/R = DeltaU/U + DeltaI/I",
        description="Use when resistance is calculated by R=U/I and U, I have absolute uncertainties.",
        quantity_types=["voltage", "current", "voltage_uncertainty", "current_uncertainty", "absolute_error"],
        query_types=["absolute_error", "resistance_error"],
        tags=["measurement_error", "uncertainty", "resistance", "voltage", "current"],
        keywords=["R = U/I", "resistance uncertainty", "absolute error of R", "voltage current uncertainty"],
        schema_template=_schema(
            "resistance_uncertainty_quotient",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "dU1", "type": "voltage_uncertainty", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "I1", "type": "current", "role": "given", "value": "<number>", "unit": "A"},
                {"id": "dI1", "type": "current_uncertainty", "role": "given", "value": "<number>", "unit": "A"},
                {"id": "dR_query", "type": "absolute_error", "role": "query", "value": None, "unit": "ohm", "symbol": "Delta R"},
            ],
        ),
    ),
    FormulaDoc(
        id="power_uncertainty_product",
        name="Uncertainty propagation for P = U I",
        equation="DeltaP/P = DeltaU/U + DeltaI/I",
        description="Use when power is calculated by P=UI and voltage/current have absolute uncertainties.",
        quantity_types=["voltage", "current", "voltage_uncertainty", "current_uncertainty", "percent_error", "absolute_error"],
        query_types=["percent_error", "absolute_error", "power_error"],
        tags=["measurement_error", "uncertainty", "power", "voltage", "current"],
        keywords=["relative error in power", "absolute error of power", "P = UI", "voltage current uncertainty"],
        schema_template=_schema(
            "power_uncertainty_product",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "dU1", "type": "voltage_uncertainty", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "I1", "type": "current", "role": "given", "value": "<number>", "unit": "A"},
                {"id": "dI1", "type": "current_uncertainty", "role": "given", "value": "<number>", "unit": "A"},
                {"id": "percent_query", "type": "percent_error", "role": "query", "value": None, "unit": "%"},
            ],
        ),
    ),
    FormulaDoc(
        id="resonance_check",
        name="LC/RLC resonance yes-no check",
        equation="compare f with f0 = 1/(2*pi*sqrt(LC))",
        description="Use for yes/no questions asking whether a circuit is in resonance at a given frequency.",
        quantity_types=["frequency", "inductance", "capacitance"],
        query_types=["boolean"],
        tags=["lc", "rlc", "resonance", "frequency", "yes_no"],
        keywords=["is it in resonance", "resonance at frequency", "yes or no resonance"],
        schema_template=_schema(
            "resonance_check",
            [
                {"id": "L1", "type": "inductance", "role": "given", "value": "<number>", "unit": "<H|mH>"},
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF>"},
                {"id": "f1", "type": "frequency", "role": "given", "value": "<number>", "unit": "<Hz|kHz>"},
                {"id": "answer_query", "type": "boolean", "role": "query", "value": None, "unit": ""},
            ],
        ),
    ),
    FormulaDoc(
        id="parallel_resistance",
        name="Equivalent resistance of parallel branches",
        equation="1/R = sum(1/R_i)",
        description="Use for total resistance of resistors or branches connected in parallel.",
        quantity_types=["resistance"],
        query_types=["resistance"],
        tags=["circuit", "resistance", "parallel"],
        keywords=["parallel resistance", "branches connected in parallel", "total resistance"],
        schema_template=_schema(
            "parallel_resistance",
            [
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "<ohm>"},
                {"id": "R2", "type": "resistance", "role": "given", "value": "<number>", "unit": "<ohm>"},
                {"id": "R_query", "type": "resistance", "role": "query", "value": None, "unit": "<ohm>"},
            ],
        ),
    ),

    FormulaDoc(
        id="ac_inductive_reactance",
        name="Inductive reactance",
        equation="XL = 2*pi*f*L = omega*L",
        description="Use for inductive reactance of an inductor in AC circuits.",
        quantity_types=["inductive_reactance", "inductance", "frequency", "angular_frequency"],
        query_types=["inductive_reactance", "inductance", "frequency"],
        tags=["ac", "rlc", "reactance", "inductive_reactance", "inductance", "frequency"],
        keywords=["inductive reactance", "Z_L", "XL", "reactance of inductor", "frequency inductance"],
        schema_template=_schema(
            "ac_inductive_reactance",
            [
                {"id": "L1", "type": "inductance", "role": "given", "value": "<number>", "unit": "<H|mH|uH>"},
                {"id": "f1", "type": "frequency", "role": "given", "value": "<number>", "unit": "<Hz|kHz>"},
                {"id": "XL_query", "type": "inductive_reactance", "role": "query", "value": None, "unit": "ohm"},
            ],
        ),
    ),
    FormulaDoc(
        id="ac_capacitive_reactance",
        name="Capacitive reactance",
        equation="XC = 1/(2*pi*f*C) = 1/(omega*C)",
        description="Use for capacitive reactance of a capacitor in AC circuits.",
        quantity_types=["capacitive_reactance", "capacitance", "frequency", "angular_frequency"],
        query_types=["capacitive_reactance", "capacitance", "frequency"],
        tags=["ac", "rlc", "reactance", "capacitive_reactance", "capacitance", "frequency"],
        keywords=["capacitive reactance", "Z_C", "XC", "reactance of capacitor", "frequency capacitance"],
        schema_template=_schema(
            "ac_capacitive_reactance",
            [
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF|nF>"},
                {"id": "f1", "type": "frequency", "role": "given", "value": "<number>", "unit": "<Hz|kHz>"},
                {"id": "XC_query", "type": "capacitive_reactance", "role": "query", "value": None, "unit": "ohm"},
            ],
        ),
    ),
    FormulaDoc(
        id="rlc_power_voltage_impedance_resistance",
        name="Real power in a series RLC circuit",
        equation="P = I^2 R = (U/Z)^2 R",
        description="Use for real power consumed/dissipated in a series RLC circuit when total voltage, impedance, and resistance are known.",
        quantity_types=["power", "voltage", "impedance", "resistance"],
        query_types=["power"],
        tags=["ac", "rlc", "power", "impedance", "resistance", "voltage"],
        keywords=["power consumed", "power dissipated", "RLC series", "source voltage", "impedance Z", "resistance R"],
        schema_template=_schema(
            "rlc_power_voltage_impedance_resistance",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "Z1", "type": "impedance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "P_query", "type": "power", "role": "query", "value": None, "unit": "W"},
            ],
        ),
    ),
    FormulaDoc(
        id="rlc_characteristic_from_reactance",
        name="RLC circuit characteristic from reactances",
        equation="compare XL and XC",
        description="Use to classify a series RLC circuit as inductive, capacitive, or resonant from XL and XC.",
        quantity_types=["inductive_reactance", "capacitive_reactance", "circuit_characteristic"],
        query_types=["circuit_characteristic"],
        tags=["ac", "rlc", "reactance", "characteristic", "inductive", "capacitive"],
        keywords=["circuit characteristic", "inductive or capacitive", "Z_L", "Z_C", "XL greater than XC"],
        schema_template=_schema(
            "rlc_characteristic_from_reactance",
            [
                {"id": "XL1", "type": "inductive_reactance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "XC1", "type": "capacitive_reactance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "char_query", "type": "circuit_characteristic", "role": "query", "value": None, "unit": ""},
            ],
        ),
    ),

    FormulaDoc(
        id="rlc_frequency_scaled_response",
        name="Series RLC response after frequency scaling",
        equation="XL'=k XL, XC'=XC/k, Z'=sqrt(R^2+(XL'-XC')^2)",
        description="Use when only the supply frequency is multiplied by a factor and the question asks the new RMS current, resistor voltage, component voltage, impedance, or power.",
        quantity_types=["inductive_reactance", "capacitive_reactance", "frequency_factor", "voltage", "resistance", "current", "power"],
        query_types=["current", "power", "impedance", "voltage", "resistor_voltage", "inductor_voltage", "capacitor_voltage"],
        tags=["ac", "rlc", "frequency_change", "reactance", "current", "power", "voltage"],
        keywords=["frequency is doubled", "frequency is tripled", "frequency is increased", "what is RMS current", "voltage across R", "power dissipated by R", "only frequency changes"],
        schema_template=_schema(
            "rlc_frequency_scaled_response",
            [
                {"id": "XL1", "type": "inductive_reactance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "XC1", "type": "capacitive_reactance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "k1", "type": "frequency_factor", "role": "given", "value": "<number>", "unit": ""},
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "I_query", "type": "current", "role": "query", "value": None, "unit": "A"},
            ],
        ),
    ),
    FormulaDoc(
        id="rlc_component_voltage_at_resonance",
        name="RLC component voltage at resonance",
        equation="I=U/R, XL=XC=sqrt(L/C), UL=I*XL",
        description="Use at resonance to compute voltage across the inductor or capacitor from source voltage, resistance, inductance, and capacitance.",
        quantity_types=["voltage", "inductor_voltage", "capacitor_voltage", "resistance", "inductance", "capacitance"],
        query_types=["voltage", "inductor_voltage", "capacitor_voltage"],
        tags=["ac", "rlc", "resonance", "component_voltage", "inductor_voltage", "capacitor_voltage"],
        keywords=["voltage across the inductor", "UL", "voltage across L", "voltage across the capacitor", "UC", "at resonance"],
        schema_template=_schema(
            "rlc_component_voltage_at_resonance",
            [
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "R1", "type": "resistance", "role": "given", "value": "<number>", "unit": "ohm"},
                {"id": "L1", "type": "inductance", "role": "given", "value": "<number>", "unit": "H"},
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "uF"},
                {"id": "UL_query", "type": "inductor_voltage", "role": "query", "value": None, "unit": "V", "symbol": "UL"},
            ],
        ),
    ),

    FormulaDoc(
        id="lc_natural_period",
        name="LC natural period",
        equation="T = 2*pi*sqrt(L*C)",
        description="Use for natural period of an ideal LC oscillator; also supports f=1/T and omega=2*pi/T.",
        quantity_types=["period", "time", "frequency", "angular_frequency", "inductance", "capacitance"],
        query_types=["period", "time", "frequency", "angular_frequency"],
        tags=["lc", "oscillation", "period", "frequency", "angular_frequency", "inductance", "capacitance"],
        keywords=["natural period", "period of oscillation", "oscillation period", "T = 2 pi sqrt LC", "LC circuit", "angular frequency"],
        schema_template=_schema(
            "lc_natural_period",
            [
                {"id": "L1", "type": "inductance", "role": "given", "value": "<number>", "unit": "<H|mH|uH>"},
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF|nF|pF>"},
                {"id": "T_query", "type": "period", "role": "query", "value": None, "unit": "s"},
            ],
        ),
    ),
    FormulaDoc(
        id="lc_max_voltage_charge_capacitance",
        name="LC maximum voltage from maximum charge",
        equation="Umax = Qmax/C",
        description="Use when maximum capacitor charge and capacitance are given and maximum voltage is asked.",
        quantity_types=["voltage", "charge", "charge_amplitude", "capacitance"],
        query_types=["voltage", "voltage_amplitude"],
        tags=["lc", "capacitor", "maximum", "charge", "voltage", "capacitance"],
        keywords=["maximum charge", "maximum voltage", "Qmax", "Umax", "capacitor plates"],
        schema_template=_schema(
            "lc_max_voltage_charge_capacitance",
            [
                {"id": "Qmax", "type": "charge_amplitude", "role": "given", "value": "<number>", "unit": "<C|mC|uC>"},
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "<F|uF>"},
                {"id": "Umax_query", "type": "voltage", "role": "query", "value": None, "unit": "V"},
            ],
        ),
    ),
    FormulaDoc(
        id="lc_magnetic_energy_current_time",
        name="LC magnetic energy from harmonic current",
        equation="Wm = 1/2*L*(I0*cos(omega*t+phi))^2",
        description="Use for magnetic energy at a time when current is given as a cosine function.",
        quantity_types=["energy", "inductance", "current", "current_amplitude", "angular_frequency", "time", "phase"],
        query_types=["energy"],
        tags=["lc", "inductor", "magnetic_energy", "time_domain", "current", "cos"],
        keywords=["magnetic energy at time", "current as a function of time", "I0 cos", "cos omega t", "instantaneous magnetic energy"],
        schema_template=_schema(
            "lc_magnetic_energy_current_time",
            [
                {"id": "L1", "type": "inductance", "role": "given", "value": "<number>", "unit": "H"},
                {"id": "I0", "type": "current_amplitude", "role": "given", "value": "<number>", "unit": "A"},
                {"id": "omega1", "type": "angular_frequency", "role": "given", "value": "<number>", "unit": "rad/s"},
                {"id": "t1", "type": "time", "role": "given", "value": "<number>", "unit": "s"},
                {"id": "Wm_query", "type": "energy", "role": "query", "value": None, "unit": "J"},
            ],
        ),
    ),
    FormulaDoc(
        id="lc_energy_complement",
        name="LC complementary energy",
        equation="Wm = Wtotal - We, or We = Wtotal - Wm",
        description="Use when total LC energy and one instantaneous energy are known, and the other energy is asked.",
        quantity_types=["energy", "total_energy", "capacitance", "voltage", "inductance", "current"],
        query_types=["energy"],
        tags=["lc", "energy", "conservation", "complement", "electric_energy", "magnetic_energy"],
        keywords=["total energy", "magnetic field energy", "electric field energy", "voltage across capacitor", "current through inductor", "remaining energy"],
        schema_template=_schema(
            "lc_energy_complement",
            [
                {"id": "W_total", "type": "total_energy", "role": "given", "value": "<number>", "unit": "J"},
                {"id": "C1", "type": "capacitance", "role": "given", "value": "<number>", "unit": "uF"},
                {"id": "U1", "type": "voltage", "role": "given", "value": "<number>", "unit": "V"},
                {"id": "Wm_query", "type": "energy", "role": "query", "value": None, "unit": "J", "symbol": "Wm"},
            ],
        ),
    ),

]


FORMULA_BY_ID: dict[str, FormulaDoc] = {formula.id: formula for formula in FORMULA_DOCS}


def list_formula_docs() -> list[FormulaDoc]:
    return list(FORMULA_DOCS)


def get_formula_doc(formula_id: str) -> FormulaDoc:
    return FORMULA_BY_ID[formula_id]
